import { Toaster } from "sonner"
import type { Metadata } from "next"
import localFont from "next/font/local"
import { Poppins } from "next/font/google"
import "./globals.css"
import { QueryProvider } from "@/components/providers/query-provider"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
})

// const geistSans = localFont({
//   src: "../../public/fonts/GeistSans.ttf",
//   variable: "--geist-font",
// })

// const geistMono = localFont({
//   src: "../../public/fonts/GeistMono.ttf",
//   variable: "--geist-font-mono",
// })

export const metadata: Metadata = {
  title: "Quran Apps",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} bg-gray-100  dark:bg-[#1c1c22]`}>
        <QueryProvider>{children}</QueryProvider>
        <Toaster />
      </body>
    </html>
  )
}
