import { Toaster } from "sonner"
import type { Metadata } from "next"
import { Poppins, Scheherazade_New, Reem_Kufi, Noto_Nastaliq_Urdu, Noto_Sans_Arabic, Amiri, Cairo } from "next/font/google"
import "./globals.css"
import { QueryProvider } from "@/components/providers/query-provider"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
})

const reemkufi = Reem_Kufi({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-reem-kufi",
})

const amiriQuran = Scheherazade_New({
  subsets: ["arabic"],
  weight: ["400"],
  variable: "--font-amiri",
})

// Font khusus untuk Asmaul Husna - lebih jelas dan mudah dibaca
const notoNastaliq = Noto_Nastaliq_Urdu({
  subsets: ["arabic"],
  weight: ["400"],
  variable: "--font-noto-nastaliq",
})

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto-sans-arabic",
})

// Font Amiri - sangat bagus untuk teks Arab, lebih jelas dan mudah dibaca
const amiri = Amiri({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-amiri-husna",
})

// Font Cairo - sangat jelas dan mudah dibaca untuk teks Arab
const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-cairo",
})

export const metadata: Metadata = {
  title: "Quran Apps",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${reemkufi.variable} ${amiriQuran.variable} ${notoNastaliq.variable} ${notoSansArabic.variable} ${amiri.variable} ${cairo.variable} bg-gray-100 dark:bg-[#1c1c22]`}
      >
        <QueryProvider>{children}</QueryProvider>
        <Toaster />
      </body>
    </html>
  )
}
