import { Toaster } from "sonner"
import type { Metadata } from "next"
import { Poppins, Scheherazade_New, Reem_Kufi } from "next/font/google"
import "./globals.css"
import { QueryProvider } from "@/components/providers/query-provider"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
})

const reemkufi = Reem_Kufi({
  subsets: ["arabic"],
  weight: ["400", "700"], // Pilih variasi font
  variable: "--font-reem-kufi",
})

const amiriQuran = Scheherazade_New({
  subsets: ["arabic"],
  weight: ["400"],
  variable: "--font-amiri",
})

export const metadata: Metadata = {
  title: "Quran Apps",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${reemkufi.variable} ${amiriQuran.variable} bg-gray-100  dark:bg-[#1c1c22]`}
      >
        <QueryProvider>{children}</QueryProvider>
        <Toaster />
      </body>
    </html>
  )
}
